"""refactor: column track_id on table noticies can be nullable

Revision ID: 1cd5289b9317
Revises: 9423b2b32906
Create Date: 2024-04-10 12:32:41.475697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd5289b9317'
down_revision: Union[str, None] = '9423b2b32906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'track_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'track_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
