CMD_MAILING = "Введите текст рассылки"
START_MAILING = "Рассылка запущена"
END_MAILING = "Рассылка завершена"
CMD_CHECK_SUBSCRIBE = "Выберите состояние проверки подписки на канал"
GET_ID_CHANNEL = "Введите id канала"
READY = "Готово"
CMD_START_TEXT = "Введите приветственное сообщение"
CMD_HELP_TEXT = "Введите текст инструкции"
